name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Before Making Python Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      - name: Test with pytest
        run: |
            python -m pytest "tests" -p no:warnings -cov=com --cov-report=xml --cov-report=html
            python -m flake8 src
            python -m black src --check
            # python -m isort src --check-only
            bandit -r src -c bandit.yaml -v

  build_and_push_backend:
    name: Build Backend Image and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: tjsullivan1/bookmarks-backend

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        file: ./Dockerfile.backend
        push: true
        tags: tjsullivan1/bookmarks-backend:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

  build_and_push_frontend:
    name: Build Frontend Image and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: tjsullivan1/bookmarks-frontend

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: tjsullivan1/bookmarks-frontend:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
